service: queue-message-array-challenge
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
functions:
  arrayChallenge:
    handler: handler.handler
    events:
      - sns:
        arn: arn:aws:sns:us-east-1:407804843649:array-challenge