service: queue-message-array-challenge
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
functions:
  challenge:
    handler: handler.handler
    events:
      - sns:
        arn: !Ref SuperTopic
        topicName: MyCustomTopic

resources:
  Resources:
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MyCustomTopic