service: queue-message-array-challenge
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
functions:
  arrayChallenge:
    handler: handler.handler
    events:
      - sqs:
        arn:
          Fn::GetAtt:
            - receiverQueue
            - Arn
resources:
  Resources:
    array-challenge:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: array-challenge